import { IconButton } from "../material-components/material.slint";
import { Button, VerticalBox, HorizontalBox, StandardTableView } from "std-widgets.slint";

export component AppWindow inherits Window
{
    title: "Stocks";
    width: 300px;
    height: 600px;

    callback update_clicked();
    callback add_clicked();
    callback remove_clicked();

    in-out property <[[StandardListViewItem]]> stocks: [];

    VerticalLayout
    {
        HorizontalLayout
        {
            Rectangle
            {
                width: 10px;
                vertical-stretch: 0;
            }
            Text
            {
                text: "Stocks";
                vertical-alignment: center;
            }
            Rectangle
            {
                horizontal-stretch: 1;
                vertical-stretch: 0;
            }
            IconButton
            {
                icon: @image-url("icons/add.svg");
                clicked=>{add_clicked()}
            }
            IconButton
            {
                icon: @image-url("icons/remove.svg");
                clicked=>{remove_clicked()}
            }
            IconButton
            {
                icon: @image-url("icons/refresh.svg");
                clicked=>{update_clicked()}
            }
        }

        StandardTableView
        {
            columns: [
                {title: "Ticker"},
                {title: "Price"},
                {title: "Change"},
            ];

            rows: root.stocks;
        }
    }
}
