import { IconButton } from "../material-components/material.slint";
import { Button, VerticalBox, HorizontalBox, StandardTableView } from "std-widgets.slint";

export component AppWindow inherits Window
{
    title: "Stocks";
    width: 300px;
    height: 600px;

    callback update_clicked();

    VerticalLayout
    {
        HorizontalLayout
        {
            Text
            {
                text: "Stocks";
            }
            Rectangle
            {
                horizontal-stretch: 1;
                vertical-stretch: 0;
            }
            Button
            {
                text: "+";
            }
            Button
            {
                text: "-";
            }
            Button
            {
                text: "↻";
            }
        }

        StandardTableView
        {
            columns: [
                {title: "Ticker"},
                {title: "Price"},
            ];

            rows: [
                [
                    {text: "BPCL"},
                    {text: "400"}
                ],
            ];
        }
    }
}
